CREATE DATABASE Exercicio_1_4;

USE Exercicio_1_4;

CREATE TABLE Artista
(
	IdArtista INT PRIMARY KEY IDENTITY,
	Nome VARCHAR(20) NOT NULL
)

CREATE TABLE Albuns
(
	IdAlbum INT PRIMARY KEY IDENTITY,
	IdArtista INT FOREIGN KEY REFERENCES Artista(IdArtista) NOT NULL,
	Titulo	VARCHAR(20) NOT NULL,
	DataLancamento VARCHAR(10) NOT NULL UNIQUE,
	Localizacao VARCHAR(20) NOT NULL,
	QtdMinutos VARCHAR(20) NOT NULL,
	Ativo VARCHAR(20) NOT NULL	
)

CREATE TABLE Estilos
(
	IdEstilo INT PRIMARY KEY IDENTITY,
	Nome VARCHAR(20) NOT NULL
)

CREATE TABLE AlbunsEstilos
(
	IdAlbum INT FOREIGN KEY REFERENCES Albuns(IdAlbum)  NOT NULL ,
	IdEstilo INT FOREIGN KEY REFERENCES Estilos(IdEstilo) NOT NULL
)

CREATE TABLE Usuarios
(
	IdUsuaria INT PRIMARY KEY IDENTITY,
	Nome VARCHAR(20) NOT NULL,
	Email VARCHAR(20) NOT NULL,
	Senha VARCHAR(20) NOT NULL UNIQUE,	
	Permissao VARCHAR(20) NOT NULL UNIQUE
)
