CREATE DATABASE Exercicio_1_2;


--USAR O BANCO DE DADOS
USE Exercicio_1_2;

--CRIAR TABELAS




CREATE TABLE Empresa
(
	IdEmpresa INT PRIMARY KEY IDENTITY,
	Nome VARCHAR(20) NOT NULL 
)

CREATE TABLE Modelo
(
	IdModelo INT PRIMARY KEY IDENTITY,
	Nome VARCHAR(20) NOT NULL
)

CREATE TABLE Marca 
(
	IdMarca INT PRIMARY KEY IDENTITY,
	Nome VARCHAR(20) NOT NULL
)

CREATE TABLE Veiculo
(
	IdVeiculo INT PRIMARY KEY IDENTITY,
	IdEmpresa INT FOREIGN KEY REFERENCES Empresa(IdEmpresa) NOT NULL UNIQUE,
	IdModelo INT FOREIGN KEY REFERENCES Modelo(IdModelo) NOT NULL UNIQUE,
	IdMarca INT FOREIGN KEY REFERENCES Marca(IdMarca) NOT NULL UNIQUE,
	Placa VARCHAR(7) NOT NULL UNIQUE
)

CREATE TABLE Cliente
(
	IdCliente INT PRIMARY KEY IDENTITY,
	Nome VARCHAR(20) NOT NULL, 
	CPF VARCHAR(11) NOT NULL UNIQUE 
)

CREATE TABLE Aluguel
(
	IdAluguel INT PRIMARY KEY IDENTITY,
	IdVeiculo INT FOREIGN KEY REFERENCES Veiculo(IdVeiculo) NOT NULL,
	IdCliente INT FOREIGN KEY REFERENCES Cliente(IdCliente) NOT NULL,
	Protocolo VARCHAR(20) NOT NULL UNIQUE 
)

SELECT * FROM Empresa
SELECT * FROM Modelo
SELECT * FROM Marca
SELECT * FROM Veiculo
SELECT * FROM Cliente
SELECT * FROM Aluguel
